from .EventEditorWidget import *
from .KicksToolWidget import *
from .LayerWidget import *
from .LogFrequencyAxisWidget import *
from .MelSpectrogramWidget import *
from .OnsetDetectionWidget import *
from .PlaybackModeWidget import *
from .SongOverviewWidget import *
from .SongSelectWidget import *
from .StackWidget import *
from .STFTLinearSpectrogramWidget import *
